# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jikai
email: 
description: > # this means to ignore newlines until "baseurl:"
  We are accustomed to the fourth year that I wanted to be at that time ? ( With great self-discipline will continue to write as their own growth diary . Will grow now that write and growth diary .
baseurl: "/jikai" # the subpath of your site, e.g. /blog
url: "http://engineer-blog.github.io" # the base hostname & protocol for your site
twitter_username: kakerukaeru
github_username: kakerukaeru

# Build settings
markdown: kramdown
